### ISSUE TITLE
Builds with BOOST_TYPE_CONVERSIONS=ON` fail on macOS

### ISSUE THREAD

**Issue by niteshbhatia008** [labstreaminglayer/App-LabRecorder#27] opened 2020-06-09 01:25 UTC
I am trying to build LabRecorded in Mac and getting build errors. The error is as follows: /labstreaminglayer/Apps/LabRecorder/src/conversions.h:37:5: error: 
      member reference type 'std::ostream' (aka 'basic_ostream<char>') is not a
      pointer; did you mean to use '.'?
        dst->sputn(reinterpret_cast<const char *>(&t), sizeof(t));
        ~~~^~
           .
/labstreaminglayer/Apps/LabRecorder/src/conversions.h:37:7: error: 
      no member named 'sputn' in 'std::__1::basic_ostream<char>'
        dst->sputn(reinterpret_cast<const char *>(&t), sizeof(t));

**Comment by cboulay** [comment] 2020-06-09 01:42
Hi thanks for the report.
Resources (i.e. my time) to work on these kinds of errors are pretty limited these days. Someone will try to get to it as soon as possible.

Is there a reason the prebuilt binaries aren't working for you?
https://github.com/labstreaminglayer/App-LabRecorder/releases/tag/1.13.0-b4

**Comment by dmedine** [comment] 2020-06-09 02:42
Looks like there is a mismatch between your compiler and the version of 
the STL that you are compiling against. I say this as someone who avoids 
development on Mac at all cost. There isn't any low hanging information 
fruit about this via google, but it looks like basic_ostream should be 
implementing streambuf which is the object with sputn as a member 
function. It could be that older compilers don't have this feature. The 
standard does change over time.

Which C++ compiler are you using? Clang? gcc? Version?

Before trying to deal with the compiler errors, though, I would follow 
cboulay's advice and just take the binary which is already compiled and 
tested.

**Comment by tstenner** [comment] 2020-06-09 07:03
That's the code path for non-standard cpu architectures (e.g. some big endian machines, but definitely nothing macOS or iOS run on).
In theory, CMake should detect that this isn't needed for you, but there are some circumstances where this could fail. If you could remove your build directory and paste the CMake log (`cmake -S /path/to/LabRecorder -B /path/to/LabRecorder/build`) I could take a look at it. You could also disable the check with `cmake -DLABRECORDER_BOOST_TYPE_CONVERSIONS=OFF -DLABRECORDER_SKIP_CPUTESTS=ON /path/to/the/builddir`.

But, as both cboulay and dmedine said the prebuilt binaries are your best bet.

**Comment by dmedine** [comment] 2020-06-11 00:00
> To my understanding, unless all the apps are built with the same pre-compiled lsl libraries, they may fail in obtaining the correct data stream.

Whoever told you this is wrong.

**Comment by niteshbhatia008** [comment] 2020-06-11 23:06
In my case for windows (64bit), any app compiled with newer lsl.dll/lib and labrecorder running on liblsl64.dll throw error such as follows when I hit the start button. 

"ERR| Stream transmission broke off (The received test-pattern samples do not match the specification. The protocol formats are likely incompatible.); re-connecting... "

If I keep same dlls in both the apps, I do not get this error.

**Comment by dmedine** [comment] 2020-06-12 00:47
Hmmm, this is troubling news indeed. Thanks for pointing it out!

I just ran a quick sanity check by firing up the ancient Mouse app from the SCCN ftp (which uses liblsl version 1.10, LSL protocol version 100) and recorded with the latest version of LabRecorder (liblsl version 1.13, protocol version 110) on the latest version of Windows 10 and had no issues. 

This error message can be generated during when an inlet connects to an outlet (https://github.com/sccn/liblsl/blob/8e257f74b98876a7b1bca7a3be25eefd146f94ab/src/data_receiver.cpp#L276-L293). There is a test pattern generated and there are if/else statements that should properly handle the cases where the LSL protocols are mismatched between sender and receiver. I have never been able to trigger this error, but I typically only use Windows and Linux and often only on very up-to-date software systems. 

@niteshbhatia008, if you can, please start a new issue in the sccn/liblsl repository (https://github.com/sccn/liblsl/tree/8e257f74b98876a7b1bca7a3be25eefd146f94ab) with details for how to reproduce this error.

**Comment by tstenner** [comment] 2020-06-12 06:49
There's already an issue for that (https://github.com/sccn/liblsl/issues/76). I couldn't reproduce the issue locally yesterday, but it seems to have cropped up very recently.

**Comment by tstenner** [comment] 2020-06-12 10:24
I reproduced the issue and fixed it. As far as I can see the commit hasn't been included in any officially released binaries so all you'd need to do is to pull the latest commit for liblsl.

**Comment by cboulay** [comment] 2020-08-12 01:30
@niteshbhatia008 The pattern mismatch was fixed in liblsl recently. The BOOST_TYPE_CONVERSIONS=ON is not something we're going to be testing in the near future. If you are still having trouble using liblsl then please open an issue there. If you are still having trouble with LabRecorder then please reopen this issue or open a new one if it's on a different topic. Thank you.

**Closed by cboulay** 2020-08-12 01:30 UTC
